server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-sidecar-node-service
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json
