server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-gateway-zuul
#zuul:
#  ignored-services: microservice-provider-user