spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: localhost1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost1
  client:
    serviceUrl:
      defaultZone: http://localhost2:8762/eureka/
---
spring:
  profiles: localhost2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost2
  client:
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/