server:
  port: 8010

#eureka的相关配置
#注册到Eureka Server上的应用名称
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: microservice-consumer-movie-ribbon-hystrix-turbine-mq
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#表示将自己的ip注册到Eureka Server上
  instance:
    prefer-ip-address: true