server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
#eureka的相关配置
#注册到Eureka Server上的应用名称
eureka:
  client:
    service-url:
      #defaultZone: http://localhost1:8761/eureka/,http://localhost2:8762/eureka/
      #defaultZone: http://user:password123@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
#表示将自己的ip注册到Eureka Server上
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 我定义的元数据
      mark: love