server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #配置Git仓库的地址
          uri: https://github.com/mark6688/springcloud_text.git



